### ISSUE TITLE
ipython notebooks

### ISSUE THREAD

**Issue by volkancirik** [keonlee9420/Stepwise_Monotonic_Multihead_Attention#1]
thanks for open-sourcing! any plans for adding a notebook with a simple application? It would immensely help me understand the usage.

**Comment by keonlee9420** [comment]
Hi @volkancirik , thanks for your attention in this repo. I just added the usage section in README.md, so please refer to it. I hope it helps.

**Comment by volkancirik** [comment]
very helpful, thanks!
